### ISSUE TITLE
finalizeBundleIPFS not used/expensive

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/webasm-solidity#101]
finalizeBundleIPFS returns a merkle root of the input files for a task. It is meant to be used by another smart contract, however there seem to be 2 issues with it:

1) It is not clear how an offchain solver is supposed to recreate the merkle root when initializing the challenge, as the data being used is different. This problem manifests itself at https://github.com/TrueBitFoundation/webasm-solidity/blob/master/contracts/interactive.sol#L125

2) The call is unoptimized. At only two files the call costs 1.5 mil gas

**Comment by mrsmkl** [comment]
1. The merkle root is just created from the code root and input roots (input data, input names, input sizes). `wasm -m -input` should generate that offline.

2. Perhaps easy to optimize by using lookup for empty subtrees.

**Comment by hswick** [comment]
@mrsmkl Can you take a look at this test and see what needs to be changed?

Currently [this](https://github.com/TrueBitFoundation/webasm-solidity/blob/merkle-root-test/test/inputs-merkle-root.js#L104) fails.

**Comment by mrsmkl** [comment]
I'll hopefully have time tomorrow to fix it. There are at least two issues:
1. the code file should only be added to the bundle when `finalizeBundleIPFS` is called
2. the root for the code should be the pre-processed code hash given by `wasm -m -input` (this is the root given by emscripten-module-wrapper)

**Comment by hswick** [comment]
Looks like the optimization reduced gas usage by 250000
