### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by mrsmkl** [TrueBitFoundation/webasm-solidity#6]
Add automated testing.

**Comment by bloodstalker** [comment]
the linux test is live. i have excluded the mac test from the build matrix until i figure out a way to get solc without building it since that times out even with travis_wait.

**Comment by mrsmkl** [comment]
The tests are not yet running properly, for some reason they complain about out of gas.

**Comment by mrsmkl** [comment]
It was because the optimization was not turned on for Solidity.
